- url: github:go-skynet/model-gallery/base.yaml
  name: 'gpt4all-j-groovy'
  description: |
    GPT-J 6B finetuned by Nomic AI on the latest GPT4All dataset. Licensed for commercial use. Fast responses.
  license: 'Apache 2.0'
  urls:
    - https://gpt4all.io
  config_file:
    backend: gpt4all-j
    context_size: 1024
    parameters:
      model: ggml-gpt4all-j-v1.3-groovy.bin
      top_k: 80
      temperature: 0.2
      top_p: 0.7
    template:
      completion: 'gpt4all-completion'
      chat: gpt4all-chat

  files:
    - filename: 'ggml-gpt4all-j-v1.3-groovy.bin'
      sha256: '3b2fd7cca97284467de0be8f638925f40cbff4c70a2e10ba1094f83bfa24d86b'
      uri: 'https://gpt4all.io/models/ggml-gpt4all-j-v1.3-groovy.bin'

  prompt_templates:
    - name: 'gpt4all-completion'
      content: |
        Complete the prompt
        ### Prompt:
        {{.Input}}
        ### Response:
    - name: 'gpt4all-chat'
      content: |
        The prompt below is a question to answer, a task to complete, or a conversation to respond to; decide which and write an appropriate response.
        ### Prompt:
        {{.Input}}
        ### Response:

- url: github:go-skynet/model-gallery/base.yaml
  name: 'whisper-base'
  license: 'MIT'
  urls:
    - https://github.com/ggerganov/whisper.cpp
    - https://huggingface.co/ggerganov/whisper.cpp

  description: |
    Port of OpenAI's Whisper model in C/C++

  config_file:
    backend: whisper
    parameters:
      model: ggml-whisper-base.bin

  files:
    - filename: 'ggml-whisper-base.bin'
      sha256: '60ed5bc3dd14eea856493d334349b405782ddcaf0028d4b5df4088345fba2efe'
      uri: 'https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.bin'
