version: '3.9'

services:
  local-ai:
    image: quay.io/go-skynet/local-ai:latest
    ports:
      - '8080:8080'
    environment:
      PRELOAD_MODELS_CONFIG: /local-ai/local-ai-config.yaml
    networks:
      - pool
    volumes:
      - ../local-ai-config.yaml:/local-ai/local-ai-config.yaml

networks:
  pool:
    driver: bridge
