version: '3.9'

services:
  db:
    image: postgres:16.1
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatgbit
    networks:
      - pool

  local-ai:
    image: quay.io/go-skynet/local-ai:latest
    profiles:
      - local-ai
    ports:
      - '8080:8080'
    environment:
      PRELOAD_MODELS_CONFIG: /local-ai/local-ai-config.yaml
    networks:
      - pool
    volumes:
      - ../local-ai-config.yaml:/local-ai/local-ai-config.yaml

networks:
  pool:
    driver: bridge
